version: "3.8"

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: rtmp_server
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80 