import React, { useState, useEffect } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { apiClient } from '../lib/api';
import { Layout } from '../components/Layout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  H1, H2, H3, H4, H5, H6,
  LargeText, MediumText, NormalText, SmallText,
  Button as DSButton,
  Badge as DSBadge,
  Card as DSCard
} from '@/components/ui/design-system';
import { 
  BookOpen, 
  Clock, 
  Brain, 
  Star, 
  Search, 
  Filter,
  Download,
  BookMarked,
  Calendar,
  User,
  TrendingUp,
  FileText,
  Zap,
  Target,
  CheckCircle,
  Info,
  ArrowRight
} from 'lucide-react';
import { toast } from 'react-hot-toast';
import { format } from 'date-fns';

interface LectureSummary {
  id: number;
  stream_id: number;
  course_id: number;
  title: string;
  summary: string;
  key_points: string[];
  topics_covered: string[];
  generated_by: string;
  confidence_score: number;
  word_count: number;
  transcription_segments_count: number;
  total_transcription_duration: number;
  generated_at: string;
  created_at: string;
  updated_at: string;
}

interface CourseSummaries {
  course_id: number;
  course_title: string;
  summaries: LectureSummary[];
  total_summaries: number;
  total_duration: number;
}

const LectureSummaries: React.FC = () => {
  const { user } = useAuth();
  const [summariesByCourse, setSummariesByCourse] = useState<CourseSummaries[]>([]);
  const [selectedSummary, setSelectedSummary] = useState<LectureSummary | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCourse, setSelectedCourse] = useState<number | null>(null);
  const [bookmarkedSummaries, setBookmarkedSummaries] = useState<Set<number>>(new Set());

  useEffect(() => {
    loadSummaries();
  }, []);

  const loadSummaries = async () => {
    try {
      setIsLoading(true);
      const response = await apiClient.request('/summaries/my-summaries');
      
      if (response.error) {
        toast.error(response.error);
        return;
      }

      setSummariesByCourse(Array.isArray(response.data) ? response.data : []);
    } catch (error) {
      console.error('Error loading summaries:', error);
      toast.error('Failed to load lecture summaries');
    } finally {
      setIsLoading(false);
    }
  };

  const viewSummary = async (summary: LectureSummary) => {
    try {
      // Mark as accessed when viewing
      await apiClient.request(`/summaries/${summary.id}`, { method: 'GET' });
      setSelectedSummary(summary);
    } catch (error) {
      console.error('Error accessing summary:', error);
      toast.error('Failed to load summary details');
    }
  };

  const toggleBookmark = async (summaryId: number) => {
    try {
      const response = await apiClient.request(`/summaries/${summaryId}/bookmark`, {
        method: 'POST'
      });

      if (response.error) {
        toast.error(response.error);
        return;
      }

      const isBookmarked = (response.data as any)?.is_bookmarked;
      const newBookmarked = new Set(bookmarkedSummaries);
      
      if (isBookmarked) {
        newBookmarked.add(summaryId);
        toast.success('Summary bookmarked');
      } else {
        newBookmarked.delete(summaryId);
        toast.success('Bookmark removed');
      }
      
      setBookmarkedSummaries(newBookmarked);
    } catch (error) {
      console.error('Error toggling bookmark:', error);
      toast.error('Failed to update bookmark');
    }
  };

  const downloadSummary = (summary: LectureSummary) => {
    const content = `
# ${summary.title}

**Generated:** ${format(new Date(summary.generated_at), 'PPP')}
**Course:** ${summariesByCourse.find(c => c.course_id === summary.course_id)?.course_title}
**Duration:** ${Math.round(summary.total_transcription_duration)} minutes
**Confidence Score:** ${(summary.confidence_score * 100).toFixed(1)}%

## Summary

${summary.summary}

## Key Points

${summary.key_points.map(point => `• ${point}`).join('\n')}

## Topics Covered

${summary.topics_covered.map(topic => `• ${topic}`).join('\n')}

---
Generated by ${summary.generated_by} AI • Word count: ${summary.word_count}
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${summary.title.replace(/[^a-zA-Z0-9]/g, '_')}_summary.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success('Summary downloaded');
  };

  const filteredSummaries = summariesByCourse.filter(courseSummaries => {
    if (selectedCourse && courseSummaries.course_id !== selectedCourse) return false;
    
    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      return (
        courseSummaries.course_title.toLowerCase().includes(query) ||
        courseSummaries.summaries.some(summary => 
          summary.title.toLowerCase().includes(query) ||
          summary.summary.toLowerCase().includes(query) ||
          summary.topics_covered.some(topic => topic.toLowerCase().includes(query))
        )
      );
    }
    
    return true;
  });

  const allSummaries = filteredSummaries.flatMap(course => 
    course.summaries.map(summary => ({ ...summary, course_title: course.course_title }))
  );

  const totalSummaries = summariesByCourse.reduce((total, course) => total + course.total_summaries, 0);
  const totalDuration = summariesByCourse.reduce((total, course) => total + course.total_duration, 0);

  if (isLoading) {
    return (
      <Layout>
        <div className="container mx-auto px-4 py-8">
          <div className="flex items-center justify-center h-64">
            <div className="flex items-center space-x-2">
              <div className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin" />
              <span>Loading lecture summaries...</span>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-7xl mx-auto">
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-foreground">Lecture Summaries</h1>
              <p className="text-muted-foreground mt-2">
                AI-generated summaries of your enrolled course lectures
              </p>
            </div>
            <div className="flex items-center space-x-4">
              <div className="text-right text-sm text-muted-foreground">
                <div className="font-medium">{totalSummaries} summaries</div>
                <div>{Math.round(totalDuration)} minutes of content</div>
              </div>
            </div>
          </div>

          {summariesByCourse.length === 0 ? (
            <Alert>
              <Info className="h-4 w-4" />
              <AlertDescription>
                No lecture summaries available yet. Summaries are automatically generated after 
                live lectures with transcription enabled. Check back after attending some lectures!
              </AlertDescription>
            </Alert>
          ) : (
            <div className="grid lg:grid-cols-3 gap-6">
              {/* Sidebar - Course List and Filters */}
              <div className="lg:col-span-1 space-y-6">
                {/* Search */}
                <Card>
                  <CardHeader className="pb-4">
                    <CardTitle className="text-lg">Search & Filter</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                      <Input
                        placeholder="Search summaries..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="pl-10"
                      />
                    </div>
                    
                    {/* Course Filter */}
                    <div>
                      <label className="text-sm font-medium mb-2 block">Filter by Course</label>
                      <div className="space-y-2">
                        <Button
                          variant={selectedCourse === null ? "default" : "outline"}
                          size="sm"
                          onClick={() => setSelectedCourse(null)}
                          className="w-full justify-start"
                        >
                          All Courses
                        </Button>
                        {summariesByCourse.map((course) => (
                          <Button
                            key={course.course_id}
                            variant={selectedCourse === course.course_id ? "default" : "outline"}
                            size="sm"
                            onClick={() => setSelectedCourse(course.course_id)}
                            className="w-full justify-start"
                          >
                            <div className="flex items-center justify-between w-full">
                              <span className="truncate">{course.course_title}</span>
                              <Badge variant="secondary" className="ml-2">
                                {course.total_summaries}
                              </Badge>
                            </div>
                          </Button>
                        ))}
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Stats */}
                <Card>
                  <CardHeader className="pb-4">
                    <CardTitle className="text-lg">Your Learning Stats</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div className="text-center p-3 bg-primary/10 rounded-lg">
                        <div className="font-semibold text-primary">{totalSummaries}</div>
                        <div className="text-muted-foreground">Summaries</div>
                      </div>
                      <div className="text-center p-3 bg-green-100 text-green-800 rounded-lg">
                        <div className="font-semibold">{Math.round(totalDuration / 60)}h</div>
                        <div className="text-green-600">Content</div>
                      </div>
                      <div className="text-center p-3 bg-blue-100 text-blue-800 rounded-lg">
                        <div className="font-semibold">{summariesByCourse.length}</div>
                        <div className="text-blue-600">Courses</div>
                      </div>
                      <div className="text-center p-3 bg-purple-100 text-purple-800 rounded-lg">
                        <div className="font-semibold">{bookmarkedSummaries.size}</div>
                        <div className="text-purple-600">Bookmarked</div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Main Content */}
              <div className="lg:col-span-2">
                {selectedSummary ? (
                  /* Summary Detail View */
                  <Card>
                    <CardHeader>
                      <div className="flex items-center justify-between">
                        <Button 
                          variant="outline" 
                          onClick={() => setSelectedSummary(null)}
                          size="sm"
                        >
                          ← Back to List
                        </Button>
                        <div className="flex items-center space-x-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => toggleBookmark(selectedSummary.id)}
                          >
                            <BookMarked 
                              className={`w-4 h-4 ${bookmarkedSummaries.has(selectedSummary.id) ? 'fill-current' : ''}`} 
                            />
                          </Button>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => downloadSummary(selectedSummary)}
                          >
                            <Download className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                      <CardTitle className="text-xl">{selectedSummary.title}</CardTitle>
                      <CardDescription>
                        <div className="flex items-center space-x-4 text-sm">
                          <span className="flex items-center">
                            <Calendar className="w-4 h-4 mr-1" />
                            {format(new Date(selectedSummary.generated_at), 'PPP')}
                          </span>
                          <span className="flex items-center">
                            <Clock className="w-4 h-4 mr-1" />
                            {Math.round(selectedSummary.total_transcription_duration)} min
                          </span>
                          <Badge variant="outline">
                            {(selectedSummary.confidence_score * 100).toFixed(1)}% confidence
                          </Badge>
                        </div>
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      {/* Summary */}
                      <div>
                        <h3 className="font-semibold mb-3 flex items-center">
                          <FileText className="w-4 h-4 mr-2" />
                          Summary
                        </h3>
                        <div className="prose prose-sm max-w-none">
                          <p className="text-foreground leading-relaxed">{selectedSummary.summary}</p>
                        </div>
                      </div>

                      {/* Key Points */}
                      {selectedSummary.key_points.length > 0 && (
                        <div>
                          <h3 className="font-semibold mb-3 flex items-center">
                            <Target className="w-4 h-4 mr-2" />
                            Key Points
                          </h3>
                          <ul className="space-y-2">
                            {selectedSummary.key_points.map((point, index) => (
                              <li key={index} className="flex items-start">
                                <CheckCircle className="w-4 h-4 mr-2 mt-1 text-green-500 flex-shrink-0" />
                                <span className="text-sm">{point}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}

                      {/* Topics Covered */}
                      {selectedSummary.topics_covered.length > 0 && (
                        <div>
                          <h3 className="font-semibold mb-3 flex items-center">
                            <Brain className="w-4 h-4 mr-2" />
                            Topics Covered
                          </h3>
                          <div className="flex flex-wrap gap-2">
                            {selectedSummary.topics_covered.map((topic, index) => (
                              <Badge key={index} variant="secondary">
                                {topic}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Generation Info */}
                      <div className="pt-4 border-t text-xs text-muted-foreground">
                        <div className="flex items-center justify-between">
                          <span>Generated by {selectedSummary.generated_by} AI</span>
                          <span>{selectedSummary.word_count} words • {selectedSummary.transcription_segments_count} segments</span>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ) : (
                  /* Summary List View */
                  <div className="space-y-4">
                    {filteredSummaries.map((courseSummaries) => (
                      <Card key={courseSummaries.course_id}>
                        <CardHeader>
                          <CardTitle className="flex items-center justify-between">
                            <span className="flex items-center">
                              <BookOpen className="w-5 h-5 mr-2" />
                              {courseSummaries.course_title}
                            </span>
                            <Badge variant="outline">
                              {courseSummaries.total_summaries} summaries
                            </Badge>
                          </CardTitle>
                          <CardDescription>
                            {Math.round(courseSummaries.total_duration)} minutes of summarized content
                          </CardDescription>
                        </CardHeader>
                        <CardContent>
                          <div className="space-y-3">
                            {courseSummaries.summaries.map((summary) => (
                              <div
                                key={summary.id}
                                className="flex items-center justify-between p-3 border rounded-lg hover:bg-accent cursor-pointer transition-colors"
                                onClick={() => viewSummary(summary)}
                              >
                                <div className="flex-1">
                                  <h4 className="font-medium">{summary.title}</h4>
                                  <p className="text-sm text-muted-foreground mt-1 line-clamp-2">
                                    {summary.summary.substring(0, 150)}...
                                  </p>
                                  <div className="flex items-center space-x-3 mt-2 text-xs text-muted-foreground">
                                    <span className="flex items-center">
                                      <Clock className="w-3 h-3 mr-1" />
                                      {Math.round(summary.total_transcription_duration)} min
                                    </span>
                                    <span className="flex items-center">
                                      <Zap className="w-3 h-3 mr-1" />
                                      {(summary.confidence_score * 100).toFixed(0)}%
                                    </span>
                                    <span>{format(new Date(summary.generated_at), 'MMM d')}</span>
                                  </div>
                                </div>
                                <div className="flex items-center space-x-2 ml-4">
                                  <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      toggleBookmark(summary.id);
                                    }}
                                  >
                                    <BookMarked 
                                      className={`w-4 h-4 ${bookmarkedSummaries.has(summary.id) ? 'fill-current' : ''}`} 
                                    />
                                  </Button>
                                  <ArrowRight className="w-4 h-4 text-muted-foreground" />
                                </div>
                              </div>
                            ))}
                          </div>
                        </CardContent>
                      </Card>
                    ))}

                    {filteredSummaries.length === 0 && (
                      <Card>
                        <CardContent className="py-12 text-center">
                          <Brain className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
                          <h3 className="font-semibold mb-2">No summaries found</h3>
                          <p className="text-muted-foreground">
                            {searchQuery || selectedCourse 
                              ? 'Try adjusting your search or filter criteria.'
                              : 'Summaries will appear here after attending lectures with transcription enabled.'
                            }
                          </p>
                        </CardContent>
                      </Card>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
};

export default LectureSummaries;