version: "3.8"
services:
  mediasoup:
    build: .
    ports:
      - "3001:3001"
    container_name: mediasoup_server
    environment:
      - NODE_ENV=production
    restart: unless-stopped
